# Default values for distributed-jmeter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

master:
  ## The number of pods in the master deployment
  replicaCount: 1

server:
  ## The number of pods in the server deployment
  replicaCount: 3

image:
  ## Specify an imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: IfNotPresent

  ## The repository and image
  ## ref: https://hub.docker.com/repository/docker/vpdocker1/jmeterdistributed5.2.1
  repository: "vpdocker1/jmeterdistributed5.2.1"

  ## The tag for the image
  ## ref: https://hub.docker.com/repository/docker/vpdocker1/jmeterdistributed5.2.1/tags
  tag: v1
